{
    'name' : 'BFIL MRP CUSTOMIZATION',
    'version' : '1.0.1',
    'author' : 'rifat',
    'category' : 'Manufacturing',
    'sequence' : 1,
    'summary' : 'BFIL_MRP_CUSTOMIZATION',
    'description' : '',
    'depends' : ['base', 'mrp', 'mrp_workorder', 'mrp_account_enterprise'],
    'data' : [
        'security/ir.model.access.csv',
        'data/resume_email_template.xml',
        'data/without_resume_email_template.xml',
        'data/email_template_wc.xml',
        'views/work_center.xml',
        'views/mrp_routing_workcenter_views_inherited.xml',
        'views/mrp_bom_form_view_inherited.xml',
        'views/mrp_workorder_view_inherited.xml',
        'views/mrp_production_view_inherited.xml',
        'views/view_production_lot_form_inherited.xml',
        'views/cost_structure_report_inherited.xml',
        'report/Barcode_pdf_report.xml',
        'report/barcode_pdf_template.xml',
        'wizard/resume_pop.xml',
    ],
    'demo' : [],
    'installable' : True,
    'application': True,
    'auto_install' : False,
    'asset' : {},
}